services:
  unigo-postgres:
    image: bitnami/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    volumes:
      - ./postgres_data:/bitnami/postgresql
    networks:
      - unigo_network

  unigo-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - unigo-postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - POSTGRESQL_HOST=unigo-postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    networks:
      - unigo_network

networks:
  unigo_network:
    driver: bridge